export default {
  INITIALISE_USER: "INITIALISE_USER",

  SET_STUDENT_POST: "SET_STUDENT_POST",
  SET_STUDENT_USERS: "SET_STUDENT_USERS",
  SET_STUDENT_USER: "SET_STUDENT_USER",

  SET_TEACHER_POST: "SET_TEACHER_POST",
  SET_TEACHER_USERS: "SET_TEACHER_USERS",
  SET_TEACHER_USER: "SET_TEACHER_USER",


  GET_LAST_CHAT_BOOKING_ID: "GET_LAST_CHAT_BOOKING_ID",
  GET_USER_CURRENCY: "GET_USER_CURRENCY",
  GET_USER_INFO: "GET_USER_INFO",
  GET_STATIC_DATA: "GET_STATIC_DATA",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  ALLOW_BACK: "ALLOW_BACK",

};
